log_level = "debug"

[deploy]
# 当前的环境:dev、release
environment = "release"
# 对外提供的端口
host = "0.0.0.0:6306"
# 数据库操作超时时间
timeout = 5  # 秒为单位
# 前端文件路径
view_path = "./view"

[publish] # 任务状态实时推送，主要结合V2界面使用，任务状态会即时刷新，这块具体实现后面有时间再单独介绍一下，不配置不影响定时任务的使用
enable = false 
endpoint = "" # 实现了推送协议的地址

[micro]
region = "center" # 无特殊调整建议固定
org_id = "gophercron"  # 无特殊调整建议固定，为日后多租户feature做前提

# etcd
[etcd]
service = ["0.0.0.0:2379"]
username = ""
password = ""
dialtimeout = 5000
# etcd kv存储的key前缀 用来与其他业务做区分
prefix = "/gopher_cron"

[mysql]
service="0.0.0.0:3306"
username="itlubber"
password="itlubber"
database="gophercron"
auto_create=true # 是否自动建表

# jwt用来做api的身份校验
[jwt]
# 部署时建议替换
private_key = """
-----BEGIN PRIVATE KEY-----
MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMzza7z4KGRHB2k3
FvMnKmKjTFv6N3BYt3kNFwovRxTwWUIPp8kf5i4xMxJ/1ElqpBIirSkqHJ8c8dad
NLAuq52TOYa18qy6nD2uk+QXblv1Q4cveHQo91dpCCPzroPNzjzck9yq5GUmysQ6
F+ljW8K3parT/+8zv0kEUFWgnfWbAgMBAAECgYBd4h/3R2IRVWwyqVas+cLzvkQr
WfptT2Z0YCeutauFDviER3GfsyoY/NadYcsX+m7AE/xof+7ugC7UFd1d23MnAL4V
8gDtD3YpIT8A+4lMV3EDmmhPxdbTTNMMK29rbMxeiaawTAyaF6B/ywTzwPOkPXuX
wDR47br2TjavM0/yMQJBAOb/ayLx6Qe86P1zNMzX948+s0E+hlixwDNhH5Glagox
22NOvN3/5gA2cqBJOg9xLxGLbfGLqFn0gcKOfFMguvkCQQDjIkjwZVGOgFS4+MH2
MJOVJ7RTFrNs5+ho/iH6MVwJc6SGMhDlklWWHLxm0N6sK9FnJ6hsxlFAnbGhRbZk
ReYzAkEAqDHcaaJpAfhcUYdcL7clC4kk7mG/Yr9yajbSzLL75hZtXv7K6H5Wk1sR
1YHcI7hPBGBYmmMNHwq4nNgw0DppyQJAW+BsfMGfQfNrUf9eBkYUDMuox8tw/Oa6
Pm4+NERvJGug65+o8hRFhplNJJHs4NxAsmd6W7XE/ExNpBzc8KbNvQJAOhi61BCp
McN8bX27y5HRVwi45GWtfH5GyEWlsCrLMkXB43JeY+uukQ5tYRxFr5jwB0Ml0Gx1
0eb2zriCpjbd/w==
-----END PRIVATE KEY-----
"""

public_key = """
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDM82u8+ChkRwdpNxbzJypio0xb
+jdwWLd5DRcKL0cU8FlCD6fJH+YuMTMSf9RJaqQSIq0pKhyfHPHWnTSwLqudkzmG
tfKsupw9rpPkF25b9UOHL3h0KPdXaQgj866Dzc483JPcquRlJsrEOhfpY1vCt6Wq
0//vM79JBFBVoJ31mwIDAQAB
-----END PUBLIC KEY-----
"""
exp = 168  # token 有效期(小时)

[oidc] # oidc协议登录，授权后转为gophercron自身的登录模式，所以当前版本oidc退出登录不会影响gophercron
client_id = ""
client_secret = ""
endpoint = ""
redirect_url = ""
scopes = [""]
user_name_key = "" # 可以在 claims 中拿到用户昵称的 key